//no of ways allowed to declare an array in java programming...
class J {
    public static void main(String[] args) {
        // int[] x = {}; valid...
        // int [] x = {}; valid...
        // int []x = {}; valid...
        // int x[] = {}; C-style, also valid...
        // int x           [] = {}; still valid...
        []int x = {}; //J.java:8: error: illegal start of expression

        System.out.println(x.length);
    }
}
/*compilation error at line 8 because of invalid syntax of array declaration, in java data type should be defined first
then [] or variable.
 */