//concept: no of correct ways to declare & instantiate 2d array objects.
class K {
    public static void main(String[] args) {
        int[][] x = {{}}; //(valid)created 2d array of size 1 & at zeroth index, it is 1d-array object, which contains 0 elements.
        int[] [] x = {{}}; //valid...
        int[] []x = {{}}; //valid...
        int[] x[] = {{}}; //still valid...
        int []x[] = {{}}; //valid...
        int x[][] = {{}}; //valid...
        int x[]      [] = {{}}; //valid...
        int [][]x = {{}}; //valid...
        [][] int x = {{}}; //K.java:12: error: illegal start of expression bec. in java syntax array datatype should be declared first then brackets.

        System.out.println(x.length);
    }
}
/* Output in each cases is 1. bec. x.length is 1*/